StylesPath = .vale/styles
MinAlertLevel = warning

# sync with: vale sync
Packages = write-good

[_posts/*.md]
BasedOnStyles = write-good
write-good.Passive      = YES
write-good.TooWordy     = YES
write-good.Weasel       = YES
write-good.Cliches      = YES
write-good.ThereIs      = NO
write-good.So           = NO
write-good.Adverb       = NO
write-good.E-Prime      = NO

[about.md]
BasedOnStyles = write-good
write-good.Passive      = YES
write-good.TooWordy     = YES
write-good.Weasel       = YES
write-good.Cliches      = YES
write-good.ThereIs      = NO
write-good.So           = NO
write-good.Adverb       = NO
write-good.E-Prime      = NO
